version: "3.9"
services:
  web:
    container_name: fifi-mitch
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://postgres:password@postgres:5432/nextjsdb

  postgres:
    container_name: fifi-mitch-db
    image: postgres:15
    volumes: 
      - tmp_db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: nextjsdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password

volumes:
  tmp_db: